version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4
    ports:
     - "9200:9200"
  kibana:
    image: kibana:4.6
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch
  logstash:
    build: ./logstash
    ports:
     - "8080:8080"
    depends_on:
     - elasticsearch
    volumes:
      - ./config:/var/viiloska/config
      - ./env:/var/viiloska/env
    command: logstash -f /var/viiloska/config/pipeline.conf
