version: '2'
services:
  elastic:
    image: elasticsearch:2.4
    ports:
     - "9200:9200"
  kibana:
    image: kibana:4.6
    ports:
     - "5601:5601"
    depends_on:
     - elastic
  logstash:
    image: logstash:2.4
    ports:
     - "8080:8080"
    depends_on:
     - elastic
    volumes:
      - ./config:/config
    command: logstash -f /config/pipeline.conf
